[package]
distribution = "2201.10.0"
org = "ballerinax"
name = "hubspot.crm.commerce.discounts"
version = "1.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["hubspot", "discounts", "CRM", "commerce"] # TODO: Add keywords
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.crm.commerce.discounts"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true
